
# Database config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shifoxona
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
  data:
    web:
      pageable:
        default-page-size: 10         # Default page size.
        max-page-size: 2000           # Maximum page size to be accepted.

app:
  file:
    root-folder: fayllar